### ISSUE TITLE
Custom the SVG map color by edit the CSS

### ISSUE THREAD

**Issue by rizquuula** [VictorCazanave/react-svg-map#57]
I am a bit confused to change the color. And then I try to find the CSS file that control the color. And here it is.

```css
.svg-map {
  width: 100%;
  height: auto;
  stroke: #666;
  stroke-width: 1;
  stroke-linecap: round;
  stroke-linejoin: round; }
  .svg-map__location {
    fill: #a1d99b;
    cursor: pointer; }
    .svg-map__location:focus, .svg-map__location:hover {
      fill: #b8e2b3;
      outline: 0; }
    .svg-map__location[aria-checked=true] {
      fill: #f4bc44; }
```

I just want to say to everyone who need to modify the CSS, this is the default. 

Instead of using default  `import "react-svg-map/lib/index.css";` You can save your custom CSS.

It will really helps if there is a way to custom the color easier.
